services:
  mi-servicio:
    image: arturocabb/testspersonales:controlSmartHome
    network_mode: host
    restart: unless-stopped
    environment:
      - API_KEYLG=${API_KEYLG}
      - TELEGRAM_URL=${TELEGRAM_URL}
      - chat_id=${chat_id}
    env_file:
      - .env
    volumes:
      - ~/public/SMARTHOME:/app/.smarthome
    ports:
      - 51827:51827