name: Docker Image CI

# Detener actions de commits viejos
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update machine
      run: sudo apt update #&& sudo apt upgrade -y
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.DOCKERUSER }}
        password: ${{ secrets.DOCKERPASS }}
    - name: Build and Push Multi-Arch Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: arturocabb/testspersonales:controlSmartHome   

  deploy:
    environment: Production
    runs-on: ubuntu-latest
    # requiere que se haya completado el build
    needs: build
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SERVERSECRET }}
      SSH_USERNAME: ${{ secrets.SERVERUSERNAME }}
      SSH_SERVERIP: ${{ secrets.SERVERIP }}
      SSH_PORT: ${{ secrets.SSHPORT }}
    steps:
      - name: Update machine
        run: sudo apt update
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: make ssh directory
        run: |
          mkdir -p ~/.ssh
          ls
      - name: Create ssh key file and change permissions
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/raspberryremoto
          chmod 600 ~/.ssh/raspberryremoto
      - name: Agregar servidor a lista de hosts conocidos
        run: |
          ssh-keyscan -p $SSH_PORT $SSH_SERVERIP >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Probar conexion SSH
        run: |
          ssh -T -p $SSH_PORT -i ~/.ssh/raspberryremoto $SSH_USERNAME@$SSH_SERVERIP "echo 'SSH connection successful!'"
      - name: Copiar compose.yaml al servidor
        run: |
          rsync -avz -e "ssh -p $SSH_PORT -i ~/.ssh/raspberryremoto -o StrictHostKeyChecking=no" \
          ./compose.yaml \
          $SSH_USERNAME@$SSH_SERVERIP:/home/remoto/public/compose.yaml
      - name: Desplegar en el servidor remoto
        run: |
          ssh -p $SSH_PORT -i ~/.ssh/raspberryremoto $SSH_USERNAME@$SSH_SERVERIP << 'EOF'
            docker compose -f ~/public/compose.yaml down
            docker pull arturocabb/testspersonales:controlSmartHome
            docker compose -f ~/public/compose.yaml pull
            docker compose -f ~/public/compose.yaml up -d
          EOF
          
